
CREATE TABLE `card_order` (
  `id` int(11) UNSIGNED NOT NULL,
  `order_sn` varchar(20) NOT NULL DEFAULT '' COMMENT '订单号',
  `partner_id` int(11) NOT NULL DEFAULT '0' COMMENT '所属合作商',
  `user_id` int(11) NOT NULL DEFAULT '0' COMMENT '用户id',
  `card_id` int(11) NOT NULL DEFAULT '0' COMMENT '使用会员卡',
  `order_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '订单状态',
  `pay_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '付款状态',
  `order_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '订单类型',
  `offline_admin` int(11) NOT NULL DEFAULT '0' COMMENT '线下管理',
  `offline_note` varchar(255) DEFAULT NULL COMMENT '线下备注',
  `goods_id` int(11) NOT NULL DEFAULT '0' COMMENT '商品id',
  `goods_name` varchar(255) DEFAULT NULL COMMENT '商品名称',
  `total_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单总金额',
  `cash_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '现金支付',
  `card_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '会员卡支付',
  `discount_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '优惠金额',
  `discount_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '优惠类型',
  `discount_number` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '优惠额度',
  `goods_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品单价',
  `goods_number` int(11) NOT NULL DEFAULT '0' COMMENT '商品数量',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `pay_time` timestamp NULL DEFAULT NULL COMMENT '支付时间',
  `end_time` timestamp NULL DEFAULT NULL COMMENT '完成/结束时间',
  `buyer_remark` varchar(255) DEFAULT NULL COMMENT '买家备注'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
